name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: '!§bChromofault §3[§b1.8.9§3].zip'
        exclusions: '*.git* *.github*'
        type: .zip
        